COMP: Fix compiler error on clang c++11
When building Slicer on the default VTK repository
the following class of compiler errors needed to
be addressed.

These were a result of using the compiler
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ \

With compiler flags: -stdlib=libc++ -std=c++11

VTK/Filtering/vtkKdTree.cxx:2677:22: error: non-constant-expression
                            cannot be narrowed from type 'double' to
                            'float' in initializer list [-Wc++11-narrowing]
  float xfloat[3] = {x[0], x[1], x[2]};
                     ^~~~

Using explicit static_cast<>() casting avoid the compiler error.

Change-Id: I471b58ce67fd5224ea1d143b5478b257f7923a20