COMP: Fix Windows build removing vtkpythonmodules_pyi from the default target
Due to the following error being reported when building Slicer on Windows,
the "ALL" parameter was commented out.

Until this is addressed, this should ensure the build succeeds.

```
Creating .pyi files for vtkpythonmodules
Traceback (most recent call last):
  File "C:\path\to\S-0-build\python-install\Lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\path\to\S-0-build\python-install\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\path\to\S-0-build\VTK-build\bin\Lib\site-packages\vtkmodules\generate_pyi.py", line 37, in <module>
    from vtkmodules.vtkCommonCore import vtkObject, vtkSOADataArrayTemplate
ImportError: DLL load failed while importing vtkCommonCore: The specified module could not be found.
```