vtkhdf5: Fix build error when building on system with glic >= 2.19
A topic has been pushed on VTK gerrit: http://review.source.kitware.com/#/c/19153/

As described in [1], since _BSD_SOURCE has been deprecated,
_DEFAULT_SOURCE should now be used.

This commit fixes the following build error happening when buiding
on Ubuntu 14.04 LTS (with gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2,
GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.5)):

$ make H5detect
[...]
/home/jcfr/Projects/Slicer-Release/VTKv6/ThirdParty/hdf5/vtkhdf5/src/H5detect.c:158:1: error: unknown type name ‘sigjmp_buf’
 static H5JMP_BUF jbuf_g;

[1] http://www.sourceware.org/ml/glibc-cvs/2014-q1/msg00252.html

Change-Id: I81c4f77f0f2c505f6b4f998a2a4c3f9b5bba1d5e